# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "project_id" {
  default     = "rdcr-github-tests"
  description = "Resource's GCP Project ID"
  type        = string
}

variable "region" {
  default     = "europe-west2"
  type        = string
  description = "Region where resources should be provisioned at"
}
