# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "project_id" {
  description = "Resource's GCP Project ID"
  type        = string
}

variable "region" {
  default     = "europe-west2"
  type        = string
  description = "Region where resources should be provisioned at"
}

variable "golang_version" {
  default     = "1.15.2"
  description = "Golang version which should be used"
  type        = string
}

variable "terraform_version" {
  default     = "0.13.3"
  description = "Terraform version which should be used"
  type        = string
}

variable "terragrunt_version" {
  default     = "0.25.1"
  description = "Terragrunt version which should be used"
  type        = string
}
