# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.37.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "3.37.0"
    }
  }
}
